export const strings = {
  brand: "Pitwall",
  header: {
    project: "project",
    projects: "projects",
    age: "{age} old",
    takenAt: "Snapshot taken {at}.",
    staleFlag: "stale",
    staleNotice: "Snapshot is stale. It may no longer be true.",
  },
  band: {
    needsYou: "Needs you",
    running: "Running",
    ready: "Ready",
    parked: "Parked",
    problems: "Problems",
  },
  empty: {
    loading: "Reading the snapshot…",
    needsYou: "Nothing needs you.",
    running: "No lane is running.",
    ready: "Nothing is ready to pick up.",
    parked: "Nothing parked.",
    problems: "Every project read cleanly.",
  },
  column: {
    issue: "Issue",
    priority: "Priority",
    kind: "Kind",
    title: "Title",
    staleness: "Staleness",
    project: "Project",
    state: "State",
    lanes: "Lanes",
    scope: "Scope",
    source: "Source",
    message: "Message",
    at: "At",
  },
  caption: {
    needsYou: "Issues waiting on a decision or an access grant, by project.",
    running: "Lanes in flight, by project and state.",
    ready: "Issues ready to pick up, by project.",
    problems: "Sources that could not be read.",
  },
  kind: {
    decision: "decision",
    access: "access",
  },
  laneState: {
    working: "working",
    awaitingLander: "awaiting lander",
    stranded: "stranded",
  },
  stale: {
    unchecked: "unchecked",
    stillBlocking: "still blocking",
    likelyStale: "likely stale",
    resolved: "resolved",
    checkedAt: "checked",
    noPriority: "no priority recorded",
  },
  lane: {
    noActivity: "no activity recorded",
    more: "more",
    unassigned: "lane",
  },
  ready: {
    more: "more ready",
  },
  problems: {
    run: "run",
    console: "console",
  },
  failure: {
    heading: "Nothing to show",
    unreachable: "Could not reach pitwall serve at",
  },
  issue: {
    back: "Back to the board",
    loading: "Reading the issue…",
    vintage: "read at {at}",
    because: ", because ",
    notClassified: "Not classified — this issue is closed, and the console classifies open work only.",
    closedSince: "This issue has closed since the snapshot was taken at {at}.",
    supersededFields: "The snapshot still lists it as {status}; the fields below were read at {at}.",
    band: {
      classification: "Classification",
      staleness: "Staleness",
      description: "Description",
      notes: "Notes",
      dependencies: "Dependencies",
      origin: "Origin",
    },
    facts: {
      project: "Project",
      status: "Status",
      priority: "Priority",
      type: "Type",
      labels: "Labels",
      none: "—",
    },
    empty: {
      description: "No description was recorded.",
      notes: "No notes were recorded.",
    },
    recorded: {
      source: "As recorded in {source}",
      at: "{kind} at {location}",
    },
    stale: {
      closed: "Closed work is not checked for staleness.",
      closedCheck:
        "Recorded in the snapshot. Closed work is not re-checked, so this is not a claim about the issue as it stands.",
      neverChecked: "Nothing has checked whether this is still true.",
      noEvidence: "No evidence was recorded with the check.",
      evidence: "Evidence",
    },
    deps: {
      dependsOn: "Depends on",
      dependedOnBy: "Depended on by",
      emptyOn: "Nothing blocks it.",
      emptyBy: "Nothing depends on it.",
    },
    origin: {
      session: "Session",
      ref: "Ref",
    },
    failure: {
      unreadable: "{id} could not be read",
      missing: "{project} has no issue {id}",
      tried: "Tried",
    },
    reason: {
      "in-progress-lane": "lane {slot} is working it",
      "in-progress-no-lane": "it is in progress and no lane is working it",
      label: "it carries the label {label}",
      "umbrella-type": "its type is {issueType}",
      "umbrella-title-marker": "its title marks it as an epic",
      "umbrella-open-child": "{childId} is an open child of it",
      "blocked-open": "{ids} is open",
      "blocked-unreadable": "{ids} could not be read",
      "blocked-parent-in-progress": "its parent {parentId} is in progress",
      "stored-status": "the tracker records its status as {status}",
      default: "nothing parks, blocks or claims it",
      separator: ", ",
    },
  },
} as const;
