export const strings = {
  brand: "Pitwall",
  header: {
    project: "project",
    projects: "projects",
    age: "{age} old",
    takenAt: "Snapshot taken {at}.",
    staleFlag: "stale",
    staleNotice: "Snapshot is stale. It may no longer be true.",
    refreshFlag: "refresh failed",
    refreshNotice: "The last refresh failed. This board is {age} old and is not being updated.",
    versionLabel: "version",
    update: "{version} available",
  },
  band: {
    needsYou: "Needs you",
    running: "Running",
    ready: "Ready",
    parked: "Parked",
    today: "Today",
    problems: "Problems",
  },
  empty: {
    loading: "Reading the snapshot…",
    needsYou: "Nothing needs you.",
    running: "No lane is running.",
    ready: "Nothing is ready to pick up.",
    parked: "Nothing parked.",
    problems: "Every project read cleanly.",
  },
  today: {
    landed: "landed {count}",
    closed: "closed {count}",
    unknown: "unknown",
    unknownNotice: "Nothing computed how many landed today. This is not a count of zero.",
  },
  column: {
    issue: "Issue",
    priority: "Priority",
    kind: "Kind",
    title: "Title",
    staleness: "Staleness",
    project: "Project",
    state: "State",
    lanes: "Lanes",
    scope: "Scope",
    source: "Source",
    message: "Message",
    at: "At",
  },
  caption: {
    needsYou: "Issues waiting on a decision or an access grant, by project.",
    running: "Lanes in flight, by project and state.",
    ready: "Issues ready to pick up, by project.",
    problems: "Sources that could not be read.",
  },
  kind: {
    decision: "decision",
    access: "access",
  },
  laneState: {
    working: "working",
    awaitingLander: "awaiting lander",
    stranded: "stranded",
  },
  stale: {
    unchecked: "unchecked",
    stillBlocking: "still blocking",
    likelyStale: "likely stale",
    resolved: "resolved",
    checkedAt: "checked",
    noPriority: "no priority recorded",
  },
  lane: {
    noActivity: "no activity recorded",
    more: "more",
    unassigned: "lane",
  },
  ready: {
    more: "more ready",
  },
  filters: {
    region: "Filters",
    project: "project",
    type: "type",
    priority: "priority",
    epic: "epic",
    all: "All",
    none: {
      type: "no type",
      priority: "no priority",
      epic: "no epic",
    },
    clear: "Clear filters",
    countOf: "{shown} of {total}",
    active: "Filtered:",
    activeCount: "{shown} of {total} issues.",
    separator: " · ",
    dash: " — ",
    notFiltered: "not filtered",
    unknown: "{value} — not in this snapshot",
    empty: "No issue matches {filters}.",
    phrase: {
      project: "project {value}",
      type: "type {value}",
      priority: "priority {value}",
      epic: "epic {value}",
    },
  },
  problems: {
    run: "run",
    console: "console",
  },
  failure: {
    heading: "Nothing to show",
    unreachable: "Could not reach pitwall serve at",
  },
  actions: {
    region: "Act on this issue",
    answer: "Answer it",
    ready: "Mark it ready",
    notMine: "Not mine",
    scope: "These write to the tracker. No lane runs, nothing merges or deploys.",
    answerLabel: "Your answer",
    answerHint: "It goes on the ticket. The lane that picks this up reads it.",
    answerSubmit: "Write the answer",
    notMineLabel: "Why this is not yours",
    notMineHint: "It goes on the ticket, and it is how the board learns it classified this wrong.",
    notMineSubmit: "Write the reason",
    writing: "Writing to the tracker…",
    waiting: "Reading the issue first — these open when it has loaded.",
    doneAnswer:
      "Answer written to {id}. needs-decision and needs-access are cleared. A lane can pick it up when nothing else holds it — the board catches up at its next snapshot.",
    doneReady: "{id} is cleared for a lane. The board catches up at its next snapshot.",
    doneNotMine:
      "Reason written to {id}, and it is off your queue. The board catches up at its next snapshot.",
    failed: "{id} was not changed.",
    unreachable: "The console could not be reached, so nothing was written.",
  },
  issue: {
    back: "Back to the board",
    loading: "Reading the issue…",
    call: {
      decision: {
        standing: "Decide this — nothing else can, and nothing moves until you do.",
        stale: "Decide this, or say the decision is already made — the check below found the reason may have expired.",
      },
      access: {
        standing: "Run this yourself — no lane has the access it needs.",
        stale: "Run this, or say it is already done — the check below found the reason may have expired.",
      },
      inFlight: "Nothing for you — a lane is working it.",
      landing: {
        standing: "Nothing for you — it is waiting to be landed.",
        stale: "Its pull request merged. Close it, or record what is still open.",
      },
      ready: "Nothing for you — it is waiting for a lane to pick it up.",
      parked: "Nothing for you — it is parked: {reason}.",
      blocked: "Nothing for you — something else has to close first.",
      closed: "Nothing for you — this issue is closed.",
      latestNote: "Latest note",
    },
    notes: {
      count: "{count} notes",
      one: "1 note",
      separator: " · ",
      hint: "append-only history, newest last",
    },
    vintage: "read at {at}",
    because: ", because ",
    notClassified: "Not classified — this issue is closed, and the console classifies open work only.",
    closedSince: "This issue has closed since the snapshot was taken at {at}.",
    supersededFields: "The snapshot still lists it as {status}; the fields below were read at {at}.",
    band: {
      classification: "Classification",
      staleness: "Staleness",
      description: "Description",
      notes: "Notes",
      dependencies: "Dependencies",
      origin: "Origin",
    },
    facts: {
      project: "Project",
      status: "Status",
      priority: "Priority",
      type: "Type",
      labels: "Labels",
      none: "—",
    },
    empty: {
      description: "No description was recorded.",
      notes: "No notes were recorded.",
    },
    recorded: {
      source: "As recorded in {source}",
      at: "{kind} at {location}",
    },
    stale: {
      closed: "Closed work is not checked for staleness.",
      closedCheck:
        "Recorded in the snapshot. Closed work is not re-checked, so this is not a claim about the issue as it stands.",
      neverChecked: "Nothing has checked whether this is still true.",
      noEvidence: "Checked; nothing has changed that this check can see.",
      unresolved: {
        reference: {
          one: "1 reference could not be checked; it is recorded under Problems.",
          many: "{count} references could not be checked; they are recorded under Problems.",
        },
        precondition: {
          one: "1 precondition could not be run; it is recorded under Problems.",
          many: "{count} preconditions could not be run; they are recorded under Problems.",
        },
      },
      method:
        "This check reads the issue's own text: notes recorded after the parking label, issues and pull requests it names, and a short list of testable preconditions. It cannot see anything outside that.",
      evidence: "Evidence",
    },
    deps: {
      dependsOn: "Depends on",
      dependedOnBy: "Depended on by",
      emptyOn: "Nothing blocks it.",
      emptyBy: "Nothing depends on it.",
    },
    origin: {
      session: "Session",
      ref: "Ref",
    },
    failure: {
      unreadable: "{id} could not be read",
      missing: "{project} has no issue {id}",
      tried: "Tried",
    },
    reason: {
      "in-progress-lane": "lane {slot} is working it",
      "in-progress-no-lane": "it is in progress and no lane is working it",
      label: "it carries the label {label}",
      "umbrella-type": "its type is {issueType}",
      "umbrella-title-marker": "its title marks it as an epic",
      "umbrella-open-child": "{childId} is an open child of it",
      "blocked-open-one": "{ids} is open",
      "blocked-open-many": "{ids} are open",
      "blocked-unreadable-one": "{ids} could not be read",
      "blocked-unreadable-many": "{ids} could not be read",
      "blocked-parent-in-progress": "its parent {parentId} is in progress",
      "stored-status": "the tracker records its status as {status}",
      default: "nothing parks, blocks or claims it",
      separator: ", ",
    },
  },
} as const;
